services:
  postgres:
    image: postgres:16
    container_name: uber_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: uber
      POSTGRES_PASSWORD: 09112001
      POSTGRES_DB: uber_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    container_name: uber_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  server:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: uber_server
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: trish
      DB_PASSWORD: 09112001
      DB_NAME: uber_db
      REDIS_ADDR: redis:6379
    volumes:
      - ../:/app

volumes:
  postgres_data:
