// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Driver struct {
	ID        int64         `json:"id"`
	Username  string        `json:"username"`
	Password  string        `json:"password"`
	Status    sql.NullInt16 `json:"status"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type DriverLocationPath struct {
	ID         int64           `json:"id"`
	DriverID   int64           `json:"driver_id"`
	Lat        sql.NullFloat64 `json:"lat"`
	Long       sql.NullFloat64 `json:"long"`
	RecordedAt sql.NullTime    `json:"recorded_at"`
}

type Ride struct {
	ID          int64         `json:"id"`
	RiderID     int64         `json:"rider_id"`
	DriverID    sql.NullInt64 `json:"driver_id"`
	Status      sql.NullInt16 `json:"status"`
	PickupLat   float64       `json:"pickup_lat"`
	PickupLong  float64       `json:"pickup_long"`
	DropoffLat  float64       `json:"dropoff_lat"`
	DropoffLong float64       `json:"dropoff_long"`
	CreatedAt   sql.NullTime  `json:"created_at"`
}

type Rider struct {
	ID        int64        `json:"id"`
	Username  string       `json:"username"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"created_at"`
}
