version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: uber_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uber_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: uber_redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./server
    container_name: uber_backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
